fix: remove empty lines from docker-compose.varnish-extras.yaml, fixes #24
ddev/ddev-varnish pull request #28
Opened 2024-07-04 17:59 UTC by stasadev

## The Issue

- #24

## How This PR Solves The Issue

Uses `grep` to remove empty lines.

## Manual Testing Instructions

## Automated Testing Overview

## Related Issue Link(s)

## Release/Deployment Notes

2024-07-05 12:26 UTC, rfay reviewed
For reasons of evaluation precedence, IMO `docker-compose.varnish_extras.yaml` works better as a recommendation. I can't remember what the issue was. But that's the format I always recommend.

2024-07-05 12:45 UTC, stasadev commented
This PR does not affect the functionality of `docker-compose.varnish-extras.yaml` at all, it just makes it more presentable.

We have the same empty lines in the `.ddev/.ddev-docker-compose-base.yaml` and `~/.ddev/.router-compose.yaml` files generated by DDEV, which doesn't matter because those files are not committed.

But it matters here because you are committing this file.

2024-07-05 12:51 UTC, jedubois commented
> For reasons of evaluation precedence, IMO `docker-compose.varnish_extras.yaml` works better as a recommendation. I can't remember what the issue was. But that's the format I always recommend.

@rfay, are you referring to [this recommendation ](https://ddev.readthedocs.io/en/latest/users/extend/additional-services/#adding-custom-configuration-to-an-add-on)?

2024-07-05 13:05 UTC, rfay commented
Yes, didn't realize it made it into the docs :)

2024-07-05 13:09 UTC, stasadev commented
Ah, this talk about `_` and `-`, I didn't see that at first. Okay, let's rename it here.

2024-07-05 13:31 UTC, rfay commented
Well, the tests are improved! Don't know if the result is improved :)

2024-07-05 13:34 UTC, stasadev commented
I leave the testing to the experts 🙂.

To be honest, I don't understand how this add-on works, even after reading README.md and Varnish docs.

2024-07-22 22:56 UTC, rfay requested changes
The way to get rid of all the extra lines is to use better go templating.
For example
```
    {{- $project_tld := "ddev.site" -}}
    {{- if .DdevGlobalConfig.project_tld }}{{ $project_tld = .DdevGlobalConfig.project_tld }}{{ end }}
```

The mysterious `{{-` and `-}}` are new discoveries for me, and I usually have some trouble getting them to work the first time. But this is where all the lines come from, and this is how to clean it up.

2024-07-24 00:39 UTC, rfay requested changes
This is certainly looking great to solve the problem at hand. There's just a bit of cleanup now I think.

* In `pre_install_actions` we should remove the old `docker-compose.varnish-extra.yaml` if it exists and contains #ddev-generated
* In `removal_actions` we should remove `docker_compose.varnish_extras.yaml` if it exists and has #ddev-generated

Note that to see this in action, do a `curl -I <site>` to see the header that shows varnish has injected itself:
```
rfay@rfay-tag1-m1:~/workspace/d10$ curl -I https://d10.ddev.site
HTTP/2 200
accept-ranges: bytes
age: 0
cache-control: must-revalidate, no-cache, private
content-language: en
content-type: text/html; charset=UTF-8
date: Tue, 09 Jul 2024 21:09:47 GMT
expires: Sun, 19 Nov 1978 05:00:00 GMT
server: nginx
vary: Accept-Encoding
via: 1.1 varnish (Varnish/6.0)
x-content-type-options: nosniff
x-drupal-cache: HIT
x-drupal-dynamic-cache: MISS
x-frame-options: SAMEORIGIN
x-generator: Drupal 10 (https://www.drupal.org)
x-varnish: 163852
```

2024-08-02 03:15 UTC, rfay approved these changes
You did loads more than was casually asked in the issue! Thanks.

2024-08-02 03:16 UTC, merged